### PR TITLE
Added functions to get access to module exports

### PR DESCRIPTION
**Pull request by katyo**
Possible solution for #34

### CODE REVIEW

**Comment by koutsie** [comment]
image

**Comment by ramonGonzEdu** [comment]
FYI, you can get the patch file by adding .patch to a pull req, eg. https://github.com/bellard/quickjs/pull/35.patch

**Comment by DragonDePlatino** [comment]
This is exactly the functionality I needed for a project! Could I submit this to the mailing list and credit you as the author?

**Comment by katyo** [comment]
> This is exactly the functionality I needed for a project! Could I submit this to the mailing list and credit you as the author?

Of course!

**Comment by Symbitic** [comment]
What's the status of this?

**Comment by bellard** [comment]
done (use JS_GetModuleNamespace)

**Pull request closed without merging**
