### PR TITLE
Revert "Add `JS_HasException()` (#265)"

### PR DESCRIPTION
**Pull request by bellard**
This reverts commit db9dbd0a2b6d115c9ef3c0dc37e0c669ef4844e4.

### CODE REVIEW

**Comment by bellard** [comment]
This patch is not correct because "null" is a valid exception. Currently, the only way to test an exception is to test if JS_EXCEPTION is returned. The content of "current_exception" is undefined otherwise.

**Comment by kasperisager** [comment]
Would it be reasonable to make the contents `current_exception` of defined at all times, such as by initialising it to `JS_NULL`, so one can actually test for pending exceptions?

**Comment by kasperisager** [comment]
That's an awfully good point! Initialising it to `JS_UNINITIALIZED` instead and letting that mean "no pending exception" sounds like a plan, I can put together a PR.

**Comment by chqrlie** [comment]
> That's an awfully good point! Initialising it to `JS_UNINITIALIZED` instead and letting that mean "no pending exception" sounds like a plan, I can put together a PR.

What about `throw undefined;` ?  If any value can be thrown and should be detectable with `JS_HasException`, we should have a boolean in addition to the `current_exception` field.

**Comment by kasperisager** [comment]
@chqrlie Isn't `JS_UNDEFINED` it's own thing?

**Comment by chqrlie** [comment]
> @chqrlie Isn't `JS_UNDEFINED` it's own thing?

Yes, I was confused in my earlier comment. `JS_UNDEFINED` and `JS_UNINITIALIZED` are different types, `JS_UNINITALIZED is used for special `let` semantics and is a perfect solution for the issue at stake here.

**Pull request closed without merging**
