### PR TITLE
Improve cross platform comparability for quickjs.

### PR DESCRIPTION
**Pull request by lygstate**
Split quickjs-port.h out
Add msvc support.
Add cmake building system.

Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>
Signed-off-by: Robikz <zalewapl@gmail.com>

### CODE REVIEW

**Comment by theduke** [comment]
I'd love to see this upstream, but FYI: you have to send your patch to the mailing list here: https://www.freelists.org/list/quickjs-devel.

PRs are not accepted.

**Comment by theduke** [comment]
Ah, I see you already did so.

**Comment by knight666** [comment]
I've inadvertently done the same work in my own pull request... Needless to say that I fully endorse this one, as it seems to be cleaner and better tested!

**Comment by ramonGonzEdu** [comment]
FYI, you can get the patch file by adding .patch to a pull req, eg. https://github.com/bellard/quickjs/pull/49.patch

**Pull request closed without merging**
